<Project>

  <PropertyGroup>
    <ManagePackageVersionsCentrally>true</ManagePackageVersionsCentrally>
  </PropertyGroup>

  <ItemGroup>
    <PackageVersion Include="TUnit" Version="1.39.0" />
    <PackageVersion Include="System.Runtime.CompilerServices.Unsafe" Version="6.1.2" />
  </ItemGroup>

</Project>
